# This workflow will do a clean install of node dependencies, cache/restore them, build the source code
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# https://zellwk.com/blog/github-actions-deploy/

name: Node.js CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Clean install dependencies and build for front
        run: |
          npm ci
          npm run build:prod
        working-directory: ./frontend
      # - name: Clean install dependencies and build for backend
      #   run: |
      #     npm ci
      #     npm run build
      #   working-directory: ./
      # - run: npm test
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/sample --include "frontend/dist/***" --exclude "frontend/*"
      # ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cp ./env.json ./sample/'
      - name: Install dependencies
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd ./sample && npm i --production'
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '/home/kikuchi/.pyenv/shims/pip install -r ./sample/nlp_backend/requirements/prod.txt'
      # - name: Run migrations
      #   run: |
      #     ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'pg_dump pop_idle | gzip > "`date +"%Y%m%d"`.dump.gz"'
      #     ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd ./sample/ && npm run migrate'
      - name: Restart nginx
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'sudo systemctl restart nginx'
      - name: Restart supervisor
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'sudo supervisorctl reread'
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'sudo supervisorctl update'
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'sudo supervisorctl restart sample:'
